FROM ubuntu:24.10
ENV DEBIAN_FRONTEND    noninteractive

RUN apt-get update -qq
RUN apt-get update -qq && apt-get install -y libsqlite3-dev zlib1g-dev
RUN apt-get update -qq && apt-get install -y automake libtool git make g++ libstdc++-14-dev
COPY . /build/
WORKDIR /build
